[package]
name = "monkey_lang_lib"
version = "0.1.0"
authors = ["tuna"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii = "1.0"